[package]
edition = "2021"
name = "find-and-replace"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
text-colorizer = "1.0.0"
